/* SOLAR CIRCUIT — the asset manifest.
 *
 * None of upstream's artwork survives. Phaser3-Road ships a purple car with
 * PHASER written across its boot, roadside billboards carrying the Phaser
 * wordmark, and a blue-sky/green-grass horizon — all of which are that
 * project's branding and none of which belong on Mercury. Every PNG here is
 * generated by `scripts/build-solar-road-art.mjs`; run that script to change
 * the art, and commit what it writes. The ported *code* is still upstream's,
 * and still MIT — see public/eggs/solar-road/ATTRIBUTION.md.
 *
 * Paths go through `withBase()` because the Pages preview serves the site from
 * a subdirectory, and a computed URL that skips it 404s there. Upstream mixed
 * an absolute `/assets/…` with relative `./assets/…`; neither would survive.
 */

import { SHIP_FRAMES } from "./ships";
import { withBase } from "../../lib/base";

const ROOT = "/eggs/solar-road";

export interface ImageAsset {
  key: string;
  url: string;
}

const img = (key: string, file: string): ImageAsset => ({ key, url: withBase(`${ROOT}/${file}`) });

/** Everything the game draws, fetched by the boot scene before play starts.
 *  The whole set is ~330 KB, so unlike Polaris-Man there is nothing to gain
 *  from splitting the load across screens. */
export const ROAD_ART: readonly ImageAsset[] = [
  /* The two parallax layers. Both are 1600 wide and tile horizontally — they
     are drawn as TileSprites, not plain sprites, which is what lets them
     scroll forever without an edge coming into view. */
  img("sky", "sky.png"),
  img("ridge", "ridge.png"),
  /* The main menu's hero. Not used in play — see buildSplash in the art script
     for why it is a generated scene rather than a screenshot. */
  img("splash", "splash.png"),
  /* The three player craft, five bank frames each: level, banking left and
     right, banking hard left and right. `car.ts` swaps between them on the arrow
     keys and the menu draws them at rest. Every frame of every craft is the same
     size, which is load-bearing rather than tidy — see the note on buildHover in
     the art script. */
  ...SHIP_FRAMES.map((f) => img(f.key, f.file)),
  /* The scalable thruster flame, layered over the one baked into the frames
     above and grown with speed — see exhaust.ts. */
  img("plume", "plume.png"),
];
