/* SOLAR CIRCUIT — the three craft.
 *
 * A ship is a palette, a silhouette and four numbers. The numbers are the part
 * that matters: they scale the speed model in `car.ts`, so choosing a craft is a
 * choice about how the run will go rather than a choice of colour.
 *
 * WHAT THE FOUR DIALS DO, AND WHY THERE ARE ONLY FOUR
 *
 * Every one of them multiplies something that already existed and was already
 * tuned. That is deliberate: a ship cannot introduce a mechanic, only lean on
 * one. It keeps all three balanced against the same model, it keeps the numbers
 * comparable on the selection card, and it means a change to the speed model
 * applies to all three craft at once instead of needing three sets of edits.
 *
 *   top    scales the nominal speed, and therefore the whole ladder above it
 *   grip   scales how fast grip and surge are EARNED, not their ceilings
 *   steer  scales lateral authority
 *   boost  scales what a full meter is worth
 *
 * The three are deliberately not balanced to be equal. VECTOR is the one to
 * learn on and is second-best at everything; LANCE is faster than either in a
 * straight line and will put you in the regolith on `ANTIPODE`; BULWARK is slow
 * and can hold a line through things the other two cannot. Which is best is a
 * question about the course, which is the whole point of choosing after picking
 * a track — and the reason the selection order is ship first, track second is
 * that it is more interesting to pick a track FOR your craft than to have the
 * obvious craft handed to you by the track.
 */

/** How hard the craft is leaning: level, banking, or banking hard. `car.ts`
 *  escalates from one to the next when a turn is held. */
export type SteerLevel = -2 | -1 | 0 | 1 | 2;

export interface ShipSpec {
  /** Stable key. */
  id: string;
  name: string;
  blurb: string;
  /** Texture key prefix; frames are `<art>`, `<art>Left`, `<art>HardLeft`… */
  art: string;
  /** Accent used for this craft on the menus, matching its hull. */
  color: string;
  top: number;
  grip: number;
  steer: number;
  boost: number;
}

export const SHIPS: readonly ShipSpec[] = [
  {
    id: "vector",
    name: "VECTOR",
    blurb: "The one the fleet actually flies. No dial on it is the best on the roster and none of them is the worst, which on a course you have not learned yet is the same thing as being the fastest.",
    art: "vector",
    color: "#a58cff",
    top: 1,
    grip: 1,
    steer: 1,
    boost: 1,
  },
  {
    id: "lance",
    name: "LANCE",
    blurb: "Stripped to the spars and geared for the straights. Reaches speeds the other two cannot and earns them quickly; asks you to do the rest of the work yourself, in corners it does not want to take.",
    art: "lance",
    color: "#e0895c",
    top: 1.16,
    grip: 1.2,
    steer: 0.82,
    boost: 1.1,
  },
  {
    id: "bulwark",
    name: "BULWARK",
    blurb: "Heavy, wide-set and slow to wind up. It will not win a straight line against either of the others, and it will hold a line through the narrow sections that neither of them can.",
    art: "bulwark",
    color: "#7ce3a8",
    top: 0.9,
    grip: 0.82,
    steer: 1.28,
    boost: 1.18,
  },
];

/** Texture key for one craft at one lean. The frames are generated by
 *  `buildHover` in the art script, one set per ship, all the same size — which
 *  is load-bearing: `car.ts` swaps them on a live sprite whose resting Y came
 *  from the frame height, so a taller frame would make the craft hop. */
export function shipFrame(ship: ShipSpec, lean: SteerLevel): string {
  const suffix =
    lean === -2 ? "HardLeft" : lean === -1 ? "Left" : lean === 1 ? "Right" : lean === 2 ? "HardRight" : "";
  return ship.art + suffix;
}

/** Every texture key the three craft between them need, in load order. */
export const SHIP_FRAMES: ReadonlyArray<{ key: string; file: string }> = SHIPS.flatMap((ship) =>
  ([-2, -1, 0, 1, 2] as SteerLevel[]).map((lean) => ({
    key: shipFrame(ship, lean),
    file: `${ship.art}${lean === -2 ? "-hard-left" : lean === -1 ? "-left" : lean === 1 ? "-right" : lean === 2 ? "-hard-right" : ""}.png`,
  })),
);
